### CREATE
POST http://localhost:8000/users
Content-Type: application/json

{
    "lastname" : "Dusse",
    "firstname" : "Jean-Claude",
    "birthday" : "1985-06-11",
    "email" : "jcdusse@outlook.fr",
    "phone" : "06-75-75-75-75",
    "tree" : 1,
    "Km traveled" : 0,
}

### READ
GET http://localhost:8000/users

### READ id
GET http://localhost:8000/users/1

### UPDATE
PUT http://localhost:8000/users/1

### UPDATE
PUT http://localhost:8000/api/users/1
Content-Type: application/json

{
    "fistname" :"J-C"
}

### DELETE
DELETE http://localhost:8000/users/1

###GET 
GET http://localhost:8000/users

###POST
POST http://localhost:8000/auth/login
Content-Type: application/json

{ 
    "email": "titi@wild.com",
    "password": "azerty"
}

###GET
GET http://localhost:8000/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTM3NjM1NzQsImV4cCI6MTU5Mzg0OTk3NH0.wlTh0YSP7KcMVEbj_g-HuebVQQPGVRmQrCyZiEe4Vc0

#DELETE
DELETE http://localhost:8000/users/1

### GET REGISTER USER
GET http://localhost:8000/register

### GET REGISTER USER BY ID
GET http://localhost:8000/register/1

### CREATE USER WITH REGISTER
POST http://localhost:8000/register 
Content-Type: application/json

{
    "username" : "Titi",
    "email" : "titi@wild.com",
    "password" : "azerty"
}
