### CREATE
POST http://localhost:8000/user
Content-Type: application/json

{
    "lastname" : "Dusse",
    "firstname" : "Jean-Claude",
    "birthday" : "1985-06-11",
    "email" : "jcdusse@outlook.fr",
    "phone" : "06-75-75-75-75",
    "tree" : 1,
    "Km traveled" : 0
}

### READ
GET http://localhost:8000/api/users 

### READ id
GET http://localhost:8000/api/users/1

### UPDATE
PUT http://localhost:8000/api/users/1
Content-Type: application/json

{
    "fistname" :"J-C"
}

### DELETE
DELETE http://localhost:8000/api/users/1

### GET REGISTER USER
GET http://localhost:8000/api/register

### GET REGISTER USER BY ID
GET http://localhost:8000/api/register/1

### CREATE USER WITH REGISTER
POST http://localhost:8000/api/register 
Content-Type: application/json

{
    "username" : "Titi",
    "email" : "titi@wild.com",
    "password" : "azerty"
}