### CREATE
POST http://localhost:8000/api/users
Content-Type: application/json

{
    "lastname" : "Dusse",
    "firstname" : "Jean-Claude",
    "birthday" : "1985-06-11",
    "email" : "jcdusse@outlook.fr",
    "phone" : "06-75-75-75-75",
    "tree" : 1,
    "Km traveled" : 0,
}

### READ
GET http://localhost:8000/api/users

### READ id
GET http://localhost:8000/api/users/1

### UPDATE
PUT http://localhost:8000/api/users/1
Content-Type: application/json

{
    "fistname" :"J-C"
}

### DELETE
DELETE http://localhost:8000/api/users/1

###GET 
GET http://localhost:8000/api/login

###POST
POST http://localhost:8000/api/login/login
Content-Type: application/json

{ 
    "email": "user@user.com",
    "password": "0000"
}

###GET
GET http://localhost:8000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTM1OTMwMzksImV4cCI6MTU5MzY3OTQzOX0.XEXHSbMRk_2RFrU31PhiDprL1RxNXFKTk9d_6OexSoQ
